services:
  postgres:
    image: postgres:17-trixie
    container_name: newsletter-subscription-postgres
    restart: always
    environment:
      - POSTGRES_DB=newsletter_subscription
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql
      - db-logs:/var/log/postgresql

  keycloak-db:
    image: postgres:17-trixie
    container_name: newsletter-subscription-keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volume-data/postgresql_keycloak_data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: newsletter-subscription-keycloak
    command: [ "start-dev", "--import-realm" ]
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8091:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-db

  kafka:
    image: apache/kafka:latest
    container_name: newsletter-subscription-kafka
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_CLUSTER_ID=newsletter-subscription-cluster-1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=1
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - ./docker/kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: newsletter-subscription-kafka-ui
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8070:8080"
    depends_on:
      - kafka

  user-service:
    build:
      context: .
      dockerfile: ./user-service/src/main/docker/Dockerfile
    container_name: newsletter-subscription-user-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=newsletter_subscription
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - ENCRYPTION_SECRET_KEY=SkC9PBmRbSgm2ueOwQnTF+SCaDbVNeV+3eqCtpMA4ks=
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ns-security-realm
      - KEYCLOAK_CLIENT_ID=newsletter-subscription-client
      - KEYCLOAK_CLIENT_SECRET=sVzk1W8v6hv3qf76K2XGqcy3vmKR59kb
      - KAFKA_SERVER=kafka
      - KAFKA_EXTERNAL_PORT=9092
    volumes:
      - ./logs/:/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
      - kafka

  subscription-service:
    build:
      context: .
      dockerfile: ./subscription-service/src/main/docker/Dockerfile
    container_name: newsletter-subscription-subscription-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=newsletter_subscription
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - USER_SERVICE_URL=http://user-service:8080
      - KAFKA_SERVER=kafka
      - KAFKA_EXTERNAL_PORT=9092
    volumes:
      - ./logs/:/logs
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/src/main/docker/Dockerfile
    container_name: newsletter-subscription-api-gateway
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - SUBSCRIPTION_SERVICE_URL=http://subscription-service:8081
      - JWK_SET_URI=http://keycloak:8080/realms/ns-security-realm/protocol/openid-connect/certs
      - ISSUER_URI=http://keycloak:8080/realms/ns-security-realm
    volumes:
      - ./logs/:/logs
    ports:
      - "9000:9000"
    depends_on:
      - keycloak

volumes:
  db-data:
  db-logs:
