server:
  port: 9000

spring:
  application:
    name: api-gateway

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

services:
  items:
    user-service:
      url: ${USER_SERVICE_URL}
      path: /api/v1/user/**
      circuitBreakerId: userServiceCircuitBreaker
      fallbackPath: /fallback/user
      fallbackMessage: "User Service is currently unavailable"

    subscription-service:
      url: ${SUBSCRIPTION_SERVICE_URL}
      path: /api/v1/subscription/**
      circuitBreakerId: subscriptionServiceCircuitBreaker
      fallbackPath: /fallback/subscription
      fallbackMessage: "Subscription Service is currently unavailable"

security:
  excluded:
    urls: /actuator/**, /api/v1/user/register/**, /api/v1/user/auth/login/**, /api/v1/subscription/confirm/**

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimum-number-of-calls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
